# Generated by Django 3.2 on 2021-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='english', max_length=24),
        ),
    ]
