# Generated by Django 3.2 on 2021-05-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0002_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='franja',
            field=models.CharField(default='english', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='native_lan',
            field=models.CharField(default='english', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='nivel',
            field=models.CharField(default='english', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='pais',
            field=models.CharField(default='english', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='english', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='study_lan',
            field=models.CharField(default='english', max_length=24),
        ),
    ]
