# Generated by Django 3.2 on 2021-05-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0004_auto_20210515_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
