# Generated by Django 3.2 on 2021-05-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0006_alter_user_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=24)),
                ('description', models.CharField(default='none', max_length=255)),
            ],
        ),
    ]
