# Generated by Django 3.2 on 2021-05-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0007_studymodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymodule',
            name='title',
            field=models.CharField(default='none', max_length=36),
        ),
    ]
