# Generated by Django 3.2 on 2021-05-29 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0008_alter_studymodule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymodule',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='homework', to=settings.AUTH_USER_MODEL),
        ),
    ]
