# Generated by Django 3.2 on 2021-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0010_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='generic_profile_pic.png', null=True, upload_to=''),
        ),
    ]
