# Generated by Django 3.2 on 2021-10-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domilang', '0012_auto_20210920_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='none', max_length=1024),
        ),
    ]
